[theme]
primaryColor = "#10B981"
backgroundColor = "#090D16"
secondaryBackgroundColor = "#131C2E"
textColor = "#F3F4F6"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 25
